spring.application.name=devlog
spring.profiles.include=api
logging.level.org.springframework.security=DEBUG

SECRET_KEY=${SECRET_KEY}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
FRONTEND_URL=${FRONTEND_URL}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
GEMINI_API_KEY=${GEMINI_API_KEY}
GITHUB_TOKEN=${GITHUB_TOKEN}
SENDGRID_API_KEY=${SENDGRID_API_KEY}
SENDGRID_SENDER_EMAIL=${SENDGRID_SENDER_EMAIL}
spring.data.redis.url=${REDIS_URL}
spring.data.redis.timeout=3000ms
spring.data.redis.connect-timeout=5000ms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
springdoc.api-docs.path=/v3/api-docs
scalar.enabled=true
scalar.path=/scalar/v1
scalar.dark-mode=true
scalar.theme=purple
scalar.layout=modern
